services:
  python-app:
    build: ./python-app
    environment:
      BROKER_URL: amqp://rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy

  ruby-app:
    build: ./ruby-app
    environment:
      BROKER_URL: amqp://rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    # image: heidiks/rabbitmq-delayed-message-exchange:3.13.0-management
    # image: heidiks/rabbitmq-delayed-message-exchange:3.12.2-management
    # image: heidiks/rabbitmq-delayed-message-exchange:3.13.3-management
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    # image: heidiks/rabbitmq-delayed-message-exchange:3.12.10-management
    ports:
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q check_running
      interval: 3s
      timeout: 5s
      retries: 30
